In [3]:
import numpy as np 
py_list = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])

print(type(py_list))
print(type(np_array))
print(np_array)
print(np_array.dtype)
print(np_array.shape)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5]
int64
(5,)


In [5]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(matrix)
print("Shape: ", matrix.shape)
print('Dimension: ',matrix.ndim)
print("Total elements: ",matrix.size)
print('Data Type: ', matrix.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Dimension:  2
Total elements:  9
Data Type:  int64


In [6]:
print(np.zeros((3,4)))
print()
print(np.ones((2,3)))
print()
print(np.eye(3))
print()
print(np.arange(0,10,2))
print()
print(np.linspace(0,1,5))
print()
print(np.random.randint(0,100,(3,3)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]

[[44 36 64]
 [95 84 17]
 [23 37 71]]


In [7]:
print(np.zeros((5,4)))
print(np.ones((10,10)))
print(np.eye(5))
print(np.arange(10,30,2))
print(np.linspace(0,10,3))
print(np.random.randint(0,500,(5,5)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[10 12 14 16 18 20 22 24 26 28]
[ 0.  5. 10.]
[[ 92 107 382 318 366]
 [269 403  88 122  25]
 [397 209 481  26 472]
 [208 438 112 172  52]
 [322 201 384  45 474]]


In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])

mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print